-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.cliente_cliente_id_seq;

CREATE SEQUENCE public.cliente_cliente_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.cuenta_cuenta_id_seq;

CREATE SEQUENCE public.cuenta_cuenta_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.movimientos_movimiento_id_seq;

CREATE SEQUENCE public.movimientos_movimiento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.cliente definition

-- Drop table

-- DROP TABLE public.cliente;

CREATE TABLE public.cliente (
	cliente_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	direccion varchar(200) NULL,
	edad int4 NULL,
	genero varchar(100) NULL,
	identificacion varchar(100) NULL,
	nombre varchar(200) NULL,
	telefono varchar(100) NULL,
	contrasena varchar(100) NULL,
	estado bool NULL,
	CONSTRAINT cliente_genero_check CHECK (((genero)::text = ANY ((ARRAY['MASCULINO'::character varying, 'FEMENINO'::character varying, 'SIN_ESPECIFICAR'::character varying, 'OTRO'::character varying])::text[]))),
	CONSTRAINT cliente_pkey PRIMARY KEY (cliente_id),
	CONSTRAINT uk147rikqkb68rxqijmxxgpjwot UNIQUE (identificacion)
);


-- public.cuenta definition

-- Drop table

-- DROP TABLE public.cuenta;

CREATE TABLE public.cuenta (
	cuenta_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cliente_id int8 NOT NULL,
	numero_cuenta varchar(100) NOT NULL,
	saldo_inicial numeric(14, 4) NOT NULL,
	tipo_cuenta varchar(255) NOT NULL,
	estado bool DEFAULT true NOT NULL,
	CONSTRAINT cuenta_pkey PRIMARY KEY (cuenta_id),
	CONSTRAINT cuenta_tipo_cuenta_check CHECK (((tipo_cuenta)::text = ANY ((ARRAY['AHORROS'::character varying, 'CORRIENTE'::character varying])::text[]))),
	CONSTRAINT ukpj7ncg765kt4klndu25bwbwe4 UNIQUE (numero_cuenta)
);


-- public.movimientos definition

-- Drop table

-- DROP TABLE public.movimientos;

CREATE TABLE public.movimientos (
	movimiento_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cuenta_id int8 NOT NULL,
	fecha timestamp(6) NOT NULL,
	saldo numeric(14, 4) NOT NULL,
	tipo_movimiento varchar(255) NOT NULL,
	valor numeric(14, 4) NOT NULL,
	CONSTRAINT movimientos_pkey PRIMARY KEY (movimiento_id),
	CONSTRAINT movimientos_tipo_movimiento_check CHECK (((tipo_movimiento)::text = ANY ((ARRAY['CREDITO'::character varying, 'DEBITO'::character varying])::text[])))
);