server:
  port: 8083

spring:
  application:
    name: cig-msa-sp-onboarding-upgrade-movement
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5435/onboarding_db
    username: root
    password: rootpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      lazy-attributes-resolution: true

account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8082}